org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.14.4
minecraft_version_range=[1.14,1.16)
forge_version=28.2.26
forge_version_range=[28,)
loader_version_range=[28,)
mapping_channel=official
mapping_version=1.14.4
mod_id=reload_emc
mod_name=Reload EMC
mod_license=MIT
mod_version=0.0.0
mod_group_id=admsgenter
mod_authors=Admsgenter
mod_description=ProjectE reloadEMC command.